### ISSUE TITLE
Fix "Steam game with id 892970 is not installed"

### ISSUE THREAD

**Issue by eai04191** [Measurity/ModTemplateValheim#10]
I'm a developer who isn't good at C #. I tried to check the behavior of this template to build a mod created based on this template, but it didn't work, so I found a first aid.

Perhaps this project has been abandoned, but I'll leave a guide for anyone who wants to use it for some reason.

Currently this Build Tool does not work. The reason is that the structure of "libraryfolders.vdf" is changed.

It used to be listed with numbers as keys ([source](https://www.reddit.com/r/Steam/comments/5uqy2u/is_there_any_way_to_set_up_multiple_library/ddw8aua/?context=3)), but now it's better structured.

**current libraryfolders.vdf sample:** 
```libraryfolders.vdf
"libraryfolders"
{
	"contentstatsid"		"8073630155507702465"
	"1"
	{
		"path"		"G:\\SteamLibrary"
		"label"		""
		"contentid"		"2269125834715082803"
		"totalsize"		"2000381014016"
		"apps"
		{
			"550"		"14905356071"
			...
		}
	}
}
```

So, to get this to work, we need to look up the value in the Dictionary with the string "path" instead of the number.

https://github.com/Measurity/ModTemplateValheim/blob/cb7b2cfdd220d41b6262e4c3cafdb2f315944fbc/BuildTool/Steam.cs#L58-L79
```patch
            var steamLibraryIndex = 0;
            while (true)
            {
                steamLibraryIndex++;
---             if (!steamLibraryData.TryGetValue(steamLibraryIndex.ToString(), out var steamLibraryPath)) return null;
+++             if (!steamLibraryData.TryGetValue("path", out var steamLibraryPath)) return null;
                var manifestFile = Path.Combine(steamLibraryPath, $"steamapps/appmanifest_{appId}.acf");
                if (!File.Exists(manifestFile)) continue;

                // Validate manifest is correct.
                var game = GameDataFromAppManifest(manifestFile);
                if (game.Id != appId) continue;

                return game;
            }
        }
```
This works fine if there is only one path. If there are more than one, it probably won't work ... Write directly.
```patch
---             if (!steamLibraryData.TryGetValue(steamLibraryIndex.ToString(), out var steamLibraryPath)) return null;
+++             var steamLibraryPath = "G:\\\\SteamLibrary"; // oof
```

**Comment by geocine** [comment]
Maybe you can file a PR for the solution you gave on this issue.

**Comment by Measurity** [comment]
A PR would be helpful. I don't plan on supporting this for Valheim updates until I start playing it again but I'm ok with verifying PRs work and merging them if you're interested. Or you can fork it and apply the fix there.
