### ISSUE TITLE
Disclaimer installs mods to local game?

### ISSUE THREAD

**Issue by 1010101110** [Measurity/ModTemplateValheim#8]
i am developing a server mod. 

I go to start my valheim only to find this project has installed bepinex into my local game. 
i see readme says bepinex and moves mod to plugins folder.

but i figured that was in development environment. in the bin folder. i didn't realize this would be editing my game install.

**Comment by Measurity** [comment]
Added disclaimer to it. You can remove the affected files and verify with Steam to reset it to vanilla Valheim.
