### ISSUE TITLE
UnpatchSelf

### ISSUE THREAD

**Issue by 1010101110** [Measurity/ModTemplateValheim#9]
[Warning:  HarmonyX] UnpatchAll has been called with harmonyID=null - This will remove ALL HARMONY PATCHES. If you want to only unpatch patches created by this instance (1010101110.serversteaminfo), use UnpatchSelf() instead.

should we update Mod.cs to unpatchself?

**Comment by Measurity** [comment]
👍 fixed it.

**Comment by Faradaycodes** [comment]
What does an unpatchall mean? What specifically would be causing this? Im trying to understand the causes of these errors so i can avoid them and help others.
